version: '3.1'
services:
  nginx:
    build: ./requirements/nginx/
    ports:
      - "443:443"
      - "80:80"
    networks:
      - inception

  mariadb:
    build: ./requirements/mariadb
    env_file:
      ./.env
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress/
    ports:
      - "127.0.0.1:9000:9000"
    env_file:
      ./.env
    depends_on:
      - mariadb
      - nginx
    networks:
      - inception
    volumes:
      - wordpress:/var/www/

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/eguefif/data/mariadb"
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/eguefif/data/wordpress"

networks:
  inception:
    name: inception
    driver: bridge
