version: '3.1'
services:
  nginx:
    build: ./requirements/nginx/
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress-vol:/var/www/wp

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      ./.env
    ports:
      - "3306:3306"
    volumes:
      - mariadb-db:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    env_file:
      ./.env
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress-vol:/var/www/wp

volumes:
  mariadb-db:
    name: maria-db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/eguefif/data/mariadb"
  wordpress-vol:
    name: wordpress-vol
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/eguefif/data/wordpress"

networks:
  inception:
    name: inception
    driver: bridge
