version: '3.1'
services:
  nginx:
    build: ./requirements/nginx/
    ports:
      - "443:443"
      - "80:80"
    networks:
      - inception-network

  mariadb:
    build: ./requirements/mariadb
    env_file:
      ./.env
    volumes:
      - inception-db:/var/lib/mysql

        #  wordpress:
        #    build: ./requirements/wordpress
        #    depends_on:
        #      - mariadb
        #      - nginx
        #    restart: unless-stopped
        #    networks:
        #      - inception-network
        #      volumes:
        #        - inception-wordpress:/var/www/

volumes:
  inception-db:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: "/home/eguefif/data/mariadb"
    #inception-wordpress:

networks:
  inception-network:
    driver: bridge
