services:
  nginx:
    build: ./requirements/nginx/
    ports:
      - "443:443"
      - "80:80"
    networks:
      - inception-network

  mariadb:
    build: ./requirements/mariadb/
    ports:
      - "3306:3306"
    env_file:
      ./.env
    volumes:
      - inception:/var/lib/mysql
    networks:
      - inception-network

  wordpress:
    build: ./requirements/wordpress/
    env_file:
      ./.env
    depends_on:
      - mariadb
      - nginx
    networks:
      - inception-network

volumes:
  inception:

networks:
  inception-network:
    driver: bridge
